### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by alimukhtar53** [ZonD80/greedytorrentuniversal#1]
Hi,

i am using win 7 32-bit and configured utorrent 3.4.7( build 42330 ) and it's not working, i'am using it for iptorrents,can you pls help me out?

Thanks!!

**Comment by ZonD80** [comment]
Is it https or udp tracker?

**Comment by alimukhtar53** [comment]
its http tracker.

**Comment by ZonD80** [comment]
Please attach torrent file, so i can check

**Comment by alimukhtar53** [comment]
i am using IPT(iptorrents) and its tracker is ssl.iptorrents.com.

**Comment by ZonD80** [comment]
It is secure torrent tracker. It won't work in any case. Making it working causes MITM attack, that requires modification of certificate storage, etc. Not secure. Forget about it.

**Comment by alimukhtar53** [comment]
Thank you so much
